name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:14
                env:
                    POSTGRES_DB: test_db
                    POSTGRES_USER: test_user
                    POSTGRES_PASSWORD: test_password
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        env:
            SECRET_KEY: test
            DEBUG: True
            DB_NAME: test_db
            DB_USER: test_user
            DB_PASSWORD: test_password
            DB_HOST: localhost
            DB_PORT: 5432
            REDIS_HOST: redis://localhost
            REDIS_PORT: 6379
            CELERY_BROKER_URL: redis://localhost:6379/0
            CELERY_RESULT_BACKEND: redis://localhost:6379/0

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.11
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirment.txt
            - name: Run tests
              run: |
                  python manage.py test